### ISSUE TITLE
Object Cache ASan Error - malloc delete[] mismatch

### ISSUE THREAD

**Issue by judicaelclair** [LLNL/metall#305]
With the latest master, I get the following:

```bash
==133200==ERROR: AddressSanitizer: alloc-dealloc-mismatch (malloc vs operator delete []) on 0x7fef63e6a800
    #0 0x5587af97c308 in operator delete[](void*) /home/judicael/evopp_tool/src/clang_main/compiler-rt/lib/asan/asan_new_delete.cpp:155:3
    #1 0x5587afc589d3 in std::enable_if<is_convertible<metall::kernel::obcdetail::cache_container<long, unsigned char, 52ul, 2048ul> (*) [], metall::kernel::obcdetail::cache_container<long, unsigned char, 52ul, 2048ul> (*) []>::value, void>::type std::default_delete<metall::kernel::obcdetail::cache_container<long, unsigned char, 52ul, 2048ul> []>::operator()<metall::kernel::obcdetail::cache_container<long, unsigned char, 52ul, 2048ul>>(metall::kernel::obcdetail::cache_container<long, unsigned char, 52ul, 2048ul>*) const /include/c++/13.2.0/bits/unique_ptr.h:140:4
    #2 0x5587afc589d3 in std::unique_ptr<metall::kernel::obcdetail::cache_container<long, unsigned char, 52ul, 2048ul> [], std::default_delete<metall::kernel::obcdetail::cache_container<long, unsigned char, 52ul, 2048ul> []>>::~unique_ptr() /include/c++/13.2.0/bits/unique_ptr.h:674:4
    #3 0x5587afc589d3 in metall::kernel::object_cache<unsigned long, long, metall::kernel::bin_number_manager<2097152ul, 140737488355328ul>, metall::kernel::segment_allocator<unsigned int, unsigned long, long, 2097152ul, 140737488355328ul, metall::kernel::mmap_segment_storage<long, unsigned long>>>::~object_cache() /metall/include/metall/kernel/object_cache.hpp:466:36
    #4 0x5587afc589d3 in metall::kernel::segment_allocator<unsigned int, unsigned long, long, 2097152ul, 140737488355328ul, metall::kernel::mmap_segment_storage<long, unsigned long>>::~segment_allocator() /metall/include/metall/kernel/segment_allocator.hpp:131:41
    #5 0x5587afc584d5 in metall::kernel::manager_kernel<unsigned int, 2097152ul>::~manager_kernel() /metall/include/metall/kernel/manager_kernel_impl.ipp:36:1
    #6 0x5587afc0702f in std::default_delete<metall::kernel::manager_kernel<unsigned int, 2097152ul>>::operator()(metall::kernel::manager_kernel<unsigned int, 2097152ul>*) const /include/c++/13.2.0/bits/unique_ptr.h:99:2
    #7 0x5587afc0702f in std::unique_ptr<metall::kernel::manager_kernel<unsigned int, 2097152ul>, std::default_delete<metall::kernel::manager_kernel<unsigned int, 2097152ul>>>::~unique_ptr() /include/c++/13.2.0/bits/unique_ptr.h:404:4
    #8 0x5587afc0702f in metall::basic_manager<unsigned int, 2097152ul>::~basic_manager() /metall/include/metall/basic_manager.hpp:176:37

0x7fef63e6a800 is located 0 bytes inside of 289636352-byte region [0x7fef63e6a800,0x7fef752a2800)
allocated by thread T6 here:
    #0 0x5587af933cf7 in malloc /home/judicael/evopp_tool/src/clang_main/compiler-rt/lib/asan/asan_malloc_linux.cpp:69:3
    #1 0x5587afc96b1b in metall::kernel::object_cache<unsigned long, long, metall::kernel::bin_number_manager<2097152ul, 140737488355328ul>, metall::kernel::segment_allocator<unsigned int, unsigned long, long, 2097152ul, 140737488355328ul, metall::kernel::mmap_segment_storage<long, unsigned long>>>::priv_allocate_cache() /metall/include/metall/kernel/object_cache.hpp:584:23
    #2 0x5587afc94f18 in metall::kernel::object_cache<unsigned long, long, metall::kernel::bin_number_manager<2097152ul, 140737488355328ul>, metall::kernel::segment_allocator<unsigned int, unsigned long, long, 2097152ul, 140737488355328ul, metall::kernel::mmap_segment_storage<long, unsigned long>>>::object_cache() /metall/include/metall/kernel/object_cache.hpp:463:5
    #3 0x5587afc94f18 in metall::kernel::segment_allocator<unsigned int, unsigned long, long, 2097152ul, 140737488355328ul, metall::kernel::mmap_segment_storage<long, unsigned long>>::segment_allocator(metall::kernel::mmap_segment_storage<long, unsigned long>*) /metall/include/metall/kernel/segment_allocator.hpp:117:9
    #4 0x5587afc947c0 in metall::kernel::manager_kernel<unsigned int, 2097152ul>::manager_kernel() /metall/include/metall/kernel/manager_kernel_impl.ipp:19:7
    #5 0x5587afc4fb03 in std::__detail::_MakeUniq<metall::kernel::manager_kernel<unsigned int, 2097152ul>>::__single_object std::make_unique<metall::kernel::manager_kernel<unsigned int, 2097152ul>>() /include/c++/13.2.0/bits/unique_ptr.h:1070:34
    #6 0x5587afc4fb03 in metall::basic_manager<unsigned int, 2097152ul>::basic_manager(metall::open_read_only_t, char const*) /metall/include/metall/basic_manager.hpp:135:18

SUMMARY: AddressSanitizer: alloc-dealloc-mismatch /home/judicael/evopp_tool/src/clang_main/compiler-rt/lib/asan/asan_new_delete.cpp:155:3 in operator delete[](void*)
```

You're not supposed to mix `std::malloc` with the default `unique_ptr` deleter, namely for `object_cache::m_cache`. To fix, change `std::unique_ptr<cache_storage_type[]> m_cache` to `std::unique_ptr<cache_storage_type[], decltype([](cache_storage_type* p) { std::free(p); })> m_cache` for example.

**Comment by KIwabuchi** [comment]
Good catch! Thank you for the feedback.

I fixed the issue in this PR:
https://github.com/LLNL/metall/tree/hotfix/object_cache_free

**Comment by KIwabuchi** [comment]
The branch has been merged into the master and the develop.

**Comment by judicaelclair** [comment]
I've just checked latest master with all sanitisers (memory, address, ub), and no longer any errors, thanks
